# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-05 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ts_created', models.DateTimeField()),
                ('ts_expires', models.DateTimeField(null=True)),
                ('content', models.TextField()),
                ('content_encoding', models.TextField()),
                ('absolute_url', models.TextField()),
                ('source', models.TextField()),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='NotificationUsers',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('notification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_ids', to='notifier_api.Notifications')),
            ],
            options={
                'db_table': 'notification_user',
            },
        ),
    ]
